<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQcXF9wW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQcXF9wW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQcXF9wW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQcXF9wW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQcXF9wW\App_KernelDevDebugContainer([
    'container.build_hash' => 'QcXF9wW',
    'container.build_id' => '600d1fbc',
    'container.build_time' => 1765270386,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQcXF9wW');
