<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SPGTscPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SPGTscP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SPGTscP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
            'formatter' => ['privates', 'App\\Service\\Api\\ResourceFormatter', 'getResourceFormatterService', true],
        ], [
            'entityManager' => '?',
            'validator' => '?',
            'formatter' => 'App\\Service\\Api\\ResourceFormatter',
        ]);
    }
}
