<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MamOO97Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mamOO97' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mamOO97'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customerRepository' => ['privates', 'App\\Repository\\CustomerRepository', 'getCustomerRepositoryService', true],
            'formatter' => ['privates', 'App\\Service\\Api\\ResourceFormatter', 'getResourceFormatterService', true],
        ], [
            'customerRepository' => 'App\\Repository\\CustomerRepository',
            'formatter' => 'App\\Service\\Api\\ResourceFormatter',
        ]);
    }
}
