<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mamOO97.App\Controller\Api\CustomerController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mamOO97.App\\Controller\\Api\\CustomerController::show()'] = ($container->privates['.service_locator.mamOO97'] ?? $container->load('get_ServiceLocator_MamOO97Service'))->withContext('App\\Controller\\Api\\CustomerController::show()', $container);
    }
}
