<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerControllerdeleteVehicleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pfVP3jO.App\Controller\Api\CustomerController::deleteVehicle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pfVP3jO.App\\Controller\\Api\\CustomerController::deleteVehicle()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customerRepository' => ['privates', 'App\\Repository\\CustomerRepository', 'getCustomerRepositoryService', true],
            'vehicleRepository' => ['privates', 'App\\Repository\\VehicleRepository', 'getVehicleRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'customerRepository' => 'App\\Repository\\CustomerRepository',
            'vehicleRepository' => 'App\\Repository\\VehicleRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Api\\CustomerController::deleteVehicle()', $container);
    }
}
