<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\CustomerController' shared autowired service.
     *
     * @return \App\Controller\Api\CustomerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/ApiController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/CustomerController.php';

        $container->services['App\\Controller\\Api\\CustomerController'] = $instance = new \App\Controller\Api\CustomerController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\CustomerController', $container));

        return $instance;
    }
}
