<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SPGTscP.App\Controller\Api\CustomerController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SPGTscP.App\\Controller\\Api\\CustomerController::create()'] = ($container->privates['.service_locator.SPGTscP'] ?? $container->load('get_ServiceLocator_SPGTscPService'))->withContext('App\\Controller\\Api\\CustomerController::create()', $container);
    }
}
