<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ovgMtw4.App\Controller\Api\CustomerController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ovgMtw4.App\\Controller\\Api\\CustomerController::update()'] = ($container->privates['.service_locator.ovgMtw4'] ?? $container->load('get_ServiceLocator_OvgMtw4Service'))->withContext('App\\Controller\\Api\\CustomerController::update()', $container);
    }
}
