<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oSGv6aV.App\Controller\Api\InvoiceController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oSGv6aV.App\\Controller\\Api\\InvoiceController::index()'] = ($container->privates['.service_locator.oSGv6aV'] ?? $container->load('get_ServiceLocator_OSGv6aVService'))->withContext('App\\Controller\\Api\\InvoiceController::index()', $container);
    }
}
