<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P7nldOL.App\Controller\Api\InvoiceController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P7nldOL.App\\Controller\\Api\\InvoiceController::create()'] = ($container->privates['.service_locator.P7nldOL'] ?? $container->load('get_ServiceLocator_P7nldOLService'))->withContext('App\\Controller\\Api\\InvoiceController::create()', $container);
    }
}
