<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLookupControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\LookupController' shared autowired service.
     *
     * @return \App\Controller\Api\LookupController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/ApiController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/LookupController.php';

        $container->services['App\\Controller\\Api\\LookupController'] = $instance = new \App\Controller\Api\LookupController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\LookupController', $container));

        return $instance;
    }
}
