<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLookupControllerInvokeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9_qK_eH.App\Controller\Api\LookupController::__invoke()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9_qK_eH.App\\Controller\\Api\\LookupController::__invoke()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customerRepository' => ['privates', 'App\\Repository\\CustomerRepository', 'getCustomerRepositoryService', true],
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'formatter' => ['privates', 'App\\Service\\Api\\ResourceFormatter', 'getResourceFormatterService', true],
        ], [
            'customerRepository' => 'App\\Repository\\CustomerRepository',
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'formatter' => 'App\\Service\\Api\\ResourceFormatter',
        ]))->withContext('App\\Controller\\Api\\LookupController::__invoke()', $container);
    }
}
