<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuotationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Nd5jURD.App\Controller\Api\QuotationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Nd5jURD.App\\Controller\\Api\\QuotationController::index()'] = ($container->privates['.service_locator.Nd5jURD'] ?? $container->load('get_ServiceLocator_Nd5jURDService'))->withContext('App\\Controller\\Api\\QuotationController::index()', $container);
    }
}
