<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResourceFormatterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Api\ResourceFormatter' shared autowired service.
     *
     * @return \App\Service\Api\ResourceFormatter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Api/ResourceFormatter.php';

        return $container->privates['App\\Service\\Api\\ResourceFormatter'] = new \App\Service\Api\ResourceFormatter();
    }
}
