<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gkeqv9D.App\Controller\Api\ServiceController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gkeqv9D.App\\Controller\\Api\\ServiceController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'formatter' => ['privates', 'App\\Service\\Api\\ResourceFormatter', 'getResourceFormatterService', true],
        ], [
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
            'entityManager' => '?',
            'validator' => '?',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'formatter' => 'App\\Service\\Api\\ResourceFormatter',
        ]))->withContext('App\\Controller\\Api\\ServiceController::update()', $container);
    }
}
