<?php

namespace ContainerQcXF9wW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CY5DMVP.App\Controller\Api\ServiceController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CY5DMVP.App\\Controller\\Api\\ServiceController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
            'formatter' => ['privates', 'App\\Service\\Api\\ResourceFormatter', 'getResourceFormatterService', true],
        ], [
            'repository' => 'App\\Repository\\ServiceRepository',
            'formatter' => 'App\\Service\\Api\\ResourceFormatter',
        ]))->withContext('App\\Controller\\Api\\ServiceController::index()', $container);
    }
}
